// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_DNUex6Jz4qXX9H68JsT9gYpXkd_SBo',
    appId: '1:820791535526:web:d4508a9ecf296426951167',
    messagingSenderId: '820791535526',
    projectId: 'cli2-4fe7f',
    authDomain: 'cli2-4fe7f.firebaseapp.com',
    storageBucket: 'cli2-4fe7f.appspot.com',
    measurementId: 'G-93GTNNNGHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5O3SaZS5AuEOZulqAFBCQsTi_e_65004',
    appId: '1:820791535526:android:aabfb5e2eaaa5024951167',
    messagingSenderId: '820791535526',
    projectId: 'cli2-4fe7f',
    storageBucket: 'cli2-4fe7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUg98CLOmP2CDyc8hDee7xgplXUZfW-lw',
    appId: '1:820791535526:ios:5714016efd189cf4951167',
    messagingSenderId: '820791535526',
    projectId: 'cli2-4fe7f',
    storageBucket: 'cli2-4fe7f.appspot.com',
    iosClientId: '820791535526-s1j5ghp465ppl81ig2nml0tk3t5hshgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.test2cli',
  );
}
