// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7r8ozIVcNGsZq1uUVF4x-JNqGrAZK608',
    appId: '1:745031365608:web:f7e5c19f451a358587ea5d',
    messagingSenderId: '745031365608',
    projectId: 'fir-flutter-codelab-62930',
    authDomain: 'fir-flutter-codelab-62930.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-62930.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBApH39uhPRHVjWCEEaZ8h3rvgSeZosiRE',
    appId: '1:745031365608:android:377f8372a76f831487ea5d',
    messagingSenderId: '745031365608',
    projectId: 'fir-flutter-codelab-62930',
    storageBucket: 'fir-flutter-codelab-62930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6o4ImdQ_lfBlhURcJqVxWUpYwXx4cDkU',
    appId: '1:745031365608:ios:b05e2a6d0f32e9f287ea5d',
    messagingSenderId: '745031365608',
    projectId: 'fir-flutter-codelab-62930',
    storageBucket: 'fir-flutter-codelab-62930.appspot.com',
    iosClientId: '745031365608-1a0en16v5c4v3hbl620rr2pl6f8h6j2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharifLab11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6o4ImdQ_lfBlhURcJqVxWUpYwXx4cDkU',
    appId: '1:745031365608:ios:b05e2a6d0f32e9f287ea5d',
    messagingSenderId: '745031365608',
    projectId: 'fir-flutter-codelab-62930',
    storageBucket: 'fir-flutter-codelab-62930.appspot.com',
    iosClientId: '745031365608-1a0en16v5c4v3hbl620rr2pl6f8h6j2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharifLab11',
  );
}
