// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuim6Y-wNx2pxD8SZo3agVunpndHn_QhM',
    appId: '1:536807293085:web:d049c8dede08511bd39474',
    messagingSenderId: '536807293085',
    projectId: 'rakanlab11',
    authDomain: 'rakanlab11.firebaseapp.com',
    storageBucket: 'rakanlab11.appspot.com',
    measurementId: 'G-S8YKX7TCZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoCS4WIilYZ8IwTICZSOUZiaquarZUTQQ',
    appId: '1:536807293085:android:357f9f711f4b323cd39474',
    messagingSenderId: '536807293085',
    projectId: 'rakanlab11',
    storageBucket: 'rakanlab11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1mDc6gR6lqrBl4Bd8dRUs6bNwtd1a4V0',
    appId: '1:536807293085:ios:41b1a1e9cc3d8046d39474',
    messagingSenderId: '536807293085',
    projectId: 'rakanlab11',
    storageBucket: 'rakanlab11.appspot.com',
    iosClientId: '536807293085-f9s1lcgtsb3ftsn2qlca2s3edjr61tc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.rakanLab11',
  );
}
