// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5n8eJhg5ZUOL-UQqs8BHJIyJc2f8MDY',
    appId: '1:855123307886:web:acddf4f6f87a01f278e57f',
    messagingSenderId: '855123307886',
    projectId: 'testi-2926c',
    authDomain: 'testi-2926c.firebaseapp.com',
    storageBucket: 'testi-2926c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHeUzKy_MjfX0S88fg1Uga2xOgPYHJVkQ',
    appId: '1:855123307886:android:890fbb4179b6ddeb78e57f',
    messagingSenderId: '855123307886',
    projectId: 'testi-2926c',
    storageBucket: 'testi-2926c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSYOcZlHQkCDXqYaquiiRBkO6OWOIC15U',
    appId: '1:855123307886:ios:0d2dc2749e0b0ee878e57f',
    messagingSenderId: '855123307886',
    projectId: 'testi-2926c',
    storageBucket: 'testi-2926c.appspot.com',
    iosClientId: '855123307886-9uir5ocr16822v81skn2db6j6u6res5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.aa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSYOcZlHQkCDXqYaquiiRBkO6OWOIC15U',
    appId: '1:855123307886:ios:0d2dc2749e0b0ee878e57f',
    messagingSenderId: '855123307886',
    projectId: 'testi-2926c',
    storageBucket: 'testi-2926c.appspot.com',
    iosClientId: '855123307886-9uir5ocr16822v81skn2db6j6u6res5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.aa',
  );
}
